server {
    listen 80;
    
    # ถ้าพิมพ์ URL มีคำว่า /api/ ให้ส่งไปหา Node.js (Backend)
    location /api/ {
        proxy_pass http://backend:5000/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # ถ้าเข้าเว็บปกติ ให้ส่งไปหา React (Frontend)
    location / {
        proxy_pass http://frontend:80;
    }
}